### PR TITLE
Make less assumptions about Boost installation when building tools.

### PR DESCRIPTION
**Pull request by chenz**

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
This makes me wonder, why is boost regex needed anyways? Is the C++11 regex stuff not enough?

**Comment by matt-42** [comment]
Sorry, this was a dependency of the old iodc compiler (the @ syntaxic sugar) that is not used anymore. Too many people did not agree with this C++ pre-processing step (see https://news.ycombinator.com/item?id=8911217). I finally removed it in ba0868193814e16bc4279dc865e4c2b1645e9935.

**Comment by matt-42** [comment]
@eXpl0it3r boost::regex_replace is a bit more advance than std::regex_replace, you can pass functor formatter to do implement smarter replaces:
http://www.boost.org/doc/libs/1_57_0/libs/regex/doc/html/boo...
http://en.cppreference.com/w/cpp/regex/regex_replace

**Comment by eXpl0it3r** [comment]
I see, thanks for the explanation.

**Pull request closed without merging**
